name: hpre
version: 1.8.3.2
license: MIT
author: Galen Huntington
synopsis: Simple but handy Haskell preprocessor.
category: Language

executable:
   main: hpre.hs

cpp-options: -DBUILDING

tests:
   test:
      main: test.hs
      ghc-options: -Wall
      dependencies:
      - process
      - filepath
      - directory
      - tasty
      - tasty-golden

dependencies:
   base: 4.*
   mtl: 2.*

