name: hpre
version: 1.3.0
license: MIT
author: Galen Huntington
synopsis: Simple but handy Haskell preprocessor.
category: Language

executable:
   main: hpre.hs

dependencies:
   base: 4.*
   mtl: 2.*
