name: hpre
version: 1.8.0
license: MIT
author: Galen Huntington
synopsis: Simple but handy Haskell preprocessor.
category: Language

executable:
   main: hpre.hs

data-files:
- "tests/*"

cpp-options: -DBUILDING

tests:
   test:
      main: test.hs
      dependencies:
      - process
      - directory

dependencies:
   base: 4.*
   mtl: 2.*

